### ISSUE TITLE
Enum.NONE object

### ISSUE THREAD

**Issue by theovier** [upb-uc4/ui-web#101]
Why do we need the enum.NONE objects like `country.NONE`? It makes working with the enumeration more cumbersome in code, e.g. checks like ` const countries = Object.values(Country).filter(e => e != Country.NONE);` to display a dropdown. I realise it's meant to be the default value for this enum type but maybe there is a more elegant way to solve this. Feel free to close this issue if you feel it is nitpicking.

**Comment by bastihav** [comment]
The problem is: when we define 
```ts
interface user {
    role: Role;
}
```
and want to instantiate this, we need to pick a value of the Enum.
```ts
const user: user = {
    role = "";
}
```
is **invalid**. 

```ts
const user: user = {
    role = Role.STUDENT;
}
```
is valid.

We could argue to pick "Role.STUDENT" as default, but thats not that nice either.

Another idea is that you use the API enumeration for UI stuff (which  would not contain NONE) and we define a new Enum (similar to the entities) which "extends" the enum with NONE.
When I looked into this last week, I did not find a short and nice way to extend an enumeration, but I can look into this again. I don't want to repeat all the enumeration fields again, but import/extend them instead.

**Comment by theovier** [comment]
Could we make the user class abstract and force at instantiation to pick a more specified type (e.g. student/admin/lecturer)?
Although, I reckon this could class with the `userManagement.getAllUsers() ` method as we don't now their subtype yet, right?

IMO querying the types via API each time is less favourable than the original solution.

**Comment by bastihav** [comment]
> IMO querying the types via API each time is less favourable than the original solution.

Thats not what I meant. But we could define two enums, one with and one without, so that `const countries = Object.values(Country).filter(e => e != Country.NONE);` would not be necessary, we could just use the enum instead.
The userEntity object could then still have Country.NONE, but we would not show it in the UI, it would just be a blank value, as this is not a value of the enum.

> Although, I reckon this could class with the userManagement.getAllUsers() method as we don't now their subtype yet, right?

Not sure I understand what you mean. The method returns a UserList, which is an object with 3 attributes, a student list, lecturer list and admin list. 
However, having a Role.NONE is helpful at a few places, e.g. I instantiate a new APIResponse object for getRole, which always returns a correct role value. If the API call fails (user not found, auth error, whatever), I can return NONE. You could argue that a http statuscode between 400 and 600 would invalidate whatever is in the response, but still, I would feel weird to return "student".

**Comment by theovier** [comment]
I had a misunderstanding, sorry. 

Maybe we could solve the APIResponse problem by marking the object `optional` (like here [https://stackoverflow.com/a/17220359/6516194](url)).
