### ISSUE TITLE
No errors shown for password field at account creation

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#413]
**Reproduce:**
1. Go to create account form
2. Enter a role
3. Enter a username
4. click "Create Account"
5. see bug -> all fields with empty input are marked with errors, but not the pw field

If you enter all other information for the user correctly, then the pw field will be marked with its error on submit.
 
Maybe correlated: If all fields are empty, just the error for the username is shown

**Comment by lrschaef** [comment]
If this was a bug on our side, it was fixed by one of our changes.
If not this is a bug on your side.

**Comment by bastihav** [comment]
@lrschaef the bug is still present in development deployment. I think the confusion is, that we are first shown all validation errors concering the user and only if there are none, we are shown validation errors for the authUser. 

I think tobi talked to you last week about maybe also showing errors for the authUser. Is this implemented/considered already?

**Comment by lrschaef** [comment]
This is already implemented. The validation for User Creation is reworked on the branch that merges the endpoints in the UserService. This branch is not merged into develop atm. The earliest version of the UserService, that has the new validation will be 0.7.1.

**Comment by bastihav** [comment]
Great! We can re open this issue if there are any more problems
