### ISSUE TITLE
Matriculation selection not resetting year when changing the semester type

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#827]
![grafik](https://user-images.githubusercontent.com/63233799/106752325-9a667e80-662a-11eb-9ad7-68902a9067d7.png)

**Comment by theovier** [comment]
Why should changing the semester type reset (reset to what exactly?) the year? It seems unintuitive to me to change the semester from SS to WS and then having to readjust the year again because it changed automatically. I'd argue that users selected the year deliberately and therefore, we shouldn't change it back immediately.
